version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

nginx-proxy:
  image: nginx
  ports:
    - "8080:8080"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  depends_on:
    - auth-service
    - geo-service
  networks:
    - geoservice_backend

auth-service:
  image: your-auth-service-image:latest
  ports:
    - "5001:5001"
  environment:
    - REDIS_HOST=your-redis-host
    - REDIS_PORT=your-redis-port


  geo-service:
    build:
      context: .
      dockerfile: geo/cmd/api/Dockerfile.grpc
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - RPC_PROTOCOL=json-rpc

networks:
  geoservice_backend: